name: oss_dart
description: A dart package project can use Alibaba cloud OSS service
version: 0.1.0
author: caipeng<caipenghsxr@gmail.com>
homepage: https://github.com/caipeng-hrv/oss_dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^2.1.4
  intl: ^0.15.8
  http: ^0.12.0+4
  xml2json: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

